INSERT INTO biomas (nombre_bioma, temperatura, geografia, humedad, descripcion_de_bioma)
VALUES ("bosque","","plano","","")
("bosque florido","","plano","","")
("bosque roble oscuro","","plano","","")
("selva","","plano","","")
("pantano","","plano","","")
("sabana","","plano","","")
("taiga","","plano","","")
("taiga nevada","","plano","","")
("desierto","","plano","","")
("montañas","","plano","","")
("plana","","plano","","")
("oceano","","plano","","")
("oceano profundo","","plano","","")
("oceano frio","","plano","","")
("colinas boscosas","","plano","","")
("colinas de taiga","","plano","","")
("montañas extremas","","plano","","")
("tundra nevada","","plano","","")
("picos nevados","","plano","","")
("meseta","","plano","","")
("bioma de setas","","plano","","")
